---
driver:
  name: docker
  hostname: glance.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: glance
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - glance
  pillars:
    top.sls:
      base:
        "*":
          - glance

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] || 'ubuntu-xenial'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'trevorj/salty-whales:xenial'%>
      platform: ubuntu

suites:

  - name: cluster
    provisioner:
      pillars-from-files:
        glance.sls: tests/pillar/cluster.sls

  - name: single_ceph
    provisioner:
      pillars-from-files:
        glance.sls: tests/pillar/single_ceph.sls

  - name: single
    provisioner:
      pillars-from-files:
        glance.sls: tests/pillar/single.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
